					<div id="page_content_title">Новости</div>
					<div class="content_ge"></div>
					<div class="content">
						<div class="newslist">
							<ul>
<? foreach ($this->item_list as $item) { ?>
								<li>
									<b><a href="<?= url_for(array('controller' => 'about/news', 'action' => 'item', 'id' => $item->get_id())) ?>"><?= h($item->get_news_title()) ?></a></b>
								</li>
									<?= $item->get_news_announce() ?>
<? } ?>
							</ul>
<?= $this -> pages ?>
							<div class="clear"></div>
						</div>
						<br />
						<br />
					</div>
