			<div id="homenews">
				<div>
					<div class="floatleft"><img src="/image/sysimages/2.png" hspace="5" /></div>
					<div class="floatright"><a href="<?= url_for(array( 'controller' => 'news')) ?>"><img src="/image/sysimages/16.jpg" width="41" height="15" /></a></div>
					<div class="clear"></div>
				</div>
				<div id="homenews_content">
					<div class="homenews_left"><img src="/image/sysimages/21.jpg" width="103" height="104" hspace="6" vspace="6" /></div>
					<div class="homenews_right">
						<ul>
<? foreach ($this->item_list as $item) { ?>
							<li ifhotnews="0"><a href="<?= url_for(array('controller' => 'news', 'action' => 'item', 'id' => $item->get_id())) ?>"><?= h($item->get_news_title()) ?></a></li>
<? } ?>
						</ul>
					</div>
				</div>
			</div>
