<b>Информация о компании</b><br/><br/>
Название компании: <?= $this->from_request('title') ?><br/>
Сайт компании: <?= $this->from_request('site') ?><br/>
Город: <?= $this->from_request('city') ?><br/>
Адрес: <?= $this->from_request('address') ?><br/>
Тип компании: <?= $this->type_values[$this->from_request('title')] ?><br/><br/>

<b>Контактная информация</b><br/><br/>
ФИО: <?= $this->from_request('fio') ?><br/>
Email: <?= $this->from_request('email') ?><br/>
Skype: <?= $this->from_request('skype') ?><br/>
Телефон: <?= $this->from_request('phone') ?><br/>
