					<div id="page_content_title"><?= $this->catalogue_tree->get_catalogue_title() ?></div>
					<div class="content_ge"></div>
					<div class="content"><br />
						<div class="productlist">
							<ul>
<? foreach ($this->product_list as $product_item) { ?>
								<li hotb="<?= $product_item->get_product_leader() ?>">
									<div class="pic"><div class="hotpic"><img src="/image/sysimages/hot.gif" width="72" height="73" /></div><a href="<?= $product_item->get_product_url() ?>"><img src="<?= $product_item->get_product_image() . '/c/210/250' ?>" width="210" height="250" /></a></div>
									<div class="text"><a href="<?= $product_item->get_product_url() ?>" class="a_blue_20b"><?= $product_item->get_product_title() ?></a><br />
									<span class="txt_blue_14"><?= $product_item->get_product_code() ?></span>
									<div class="info"><?= $product_item->get_product_intro() ?></div>
									<div><a href="<?= $product_item->get_product_url() ?>"><img src="/image/sysimages/47.jpg" width="67" height="23" vspace="15" /></a></div>
									</div>
									<div class="clear"></div>
								</li>
<? } ?>
							</ul>
							<div class="clear"></div>
						</div>
						<br />
						<br />
					</div>
