			<link rel="stylesheet" href="/js/css/screen.css" type="text/css" media="screen" />
			<div id="product_detail">
				<div class="proname">Результаты сравнения</div>
				<div class="detail_top"></div>
				<div style="font-size:14px;">
<? if (count($this->product_list)) {?>
					<table border="1" cellpadding="1" cellspacing="1">
						<tr>
							<td rowspan="2" style="text-align: center;">
								Характеристики
							</td>
<? foreach ($this->product_list as $product) { ?>
							<td style="text-align: center; vertical-align: top;">
								<a href="<?= $product->get_product_url() ?>" class="a_blue_12b"><?= $product->get_product_title() ?></a>
							</td>
<? } ?>
						</tr>
						<tr>
<? foreach ($this->product_list as $product) { ?>
							<td style="text-align: center;">
								<img src="<?= $product->get_product_image() . '/c/104/104' ?>" alt="" align="top"/>&nbsp;&nbsp;<a href="<?= url_for(array('controller' => 'compare', 'action' => 'delete', 'id' => $product->get_id())) ?>" onclick="return confirm( 'Вы уверены, что хотите удалить товар из сравнения?' )"><img src="/image/delete.gif" alt=""/></a>
							</td>
<? } ?>
						</tr>
<? foreach ($this->property_group_list as $property_group) { ?>
<? 		if (count($this->property_compare_list[$property_group->get_id()])) { ?>
						<tr>
							<td colspan="<?= count($this->product_list) + 1 ?>" style="background-color: rgb(0, 59, 131);">
								<span style="font-size: 14px;"><span style="color: rgb(255, 240, 245);"><?= $property_group->get_group_title() ?></span></span>
							</td>
						</tr>
<? 			foreach ($this->property_list[$property_group->get_id()] as $property) { ?>
<? 				if (count($this->property_compare_list[$property_group->get_id()][$property->get_id()])) { ?>
						<tr<? if ($this->property_compare_list[$property_group->get_id()][$property->get_id()]['equals']) { ?> style="color: lightgray"<? } ?>>
							<td style="width: 200px;">
								<?= $property->get_property_title() ?>
							</td>
<? 					foreach ($this->product_list as $product) { ?>
							<td style="vertical-align: top; width: 190px;">
								<?= $this->property_compare_list[$property_group->get_id()][$property->get_id()][$product->get_id()] ?>
<?						if ($this->property_compare_list[$property_group->get_id()][$property->get_id()][$product->get_id()]) { ?>
								<?= $property->get_property_unit() ? ' ' . $property->get_property_unit() : '' ?>
<?						} ?>
							</td>
<? 					} ?>
						</tr>
<? 				} ?>
<? 			} ?>
<? 		} ?>
<? } ?>
					</table>
					<br/>
					<table style="width: 100%">
						<tr>
							<td style="text-align: left">
<? if ($this->in_request('show', 'diff')) { ?>
								<a href="<?= url_for(array('controller' => 'compare', 'show' => 'all')) ?>">Показать все свойства</a>
<? } else { ?>
								<a href="<?= url_for(array('controller' => 'compare', 'show' => 'diff')) ?>">Показать только отличия</a>
<? } ?>
							</td>
							<td style="text-align: right">
								<a href="<?= url_for(array('controller' => 'compare', 'action' => 'clear')) ?>">Очистить результаты сравнения</a>
							</td>
						</tr>
					</table>
<? } else { ?>
					<h3>Нет товаров для сравнения!</h3>
<? } ?>
				</div>
				<div class="clear"></div>
			</div>
