					<div id="page_content_title">Где купить</div>
					<div class="content_ge"></div>
					<div class="content">
						<div>
							<form action="" method="post" name="faqform">
								<div class="floatleft">
									<select name="city" style="width:220px;">
										<option value="">-- Выберите город --</option>
<? foreach ($this->city_on_top_list as $city) { ?>
										<option value="<?= $city->get_id() ?>"<? if ($this->in_request('city', $city->get_id())) { ?> selected="selected"<? } ?> style="color: <?= $city->get_city_capital() ? 'black' : 'gray' ?>"><?= $city->get_city_title() ?></option>
<? } ?>
<? foreach ($this->region_list as $region) { ?>
<? 		if (count($this->city_by_region_list[$region->get_id()])) { ?>
										<optgroup label="<?= $region->get_region_title() ?>">
<? 			foreach ($this->city_by_region_list[$region->get_id()] as $city) { ?>
											<option value="<?= $city->get_id() ?>"<? if ($this->in_request('city', $city->get_id())) { ?> selected="selected"<? } ?> style="color: <?= $city->get_city_capital() ? 'black' : 'gray' ?>"><?= $city->get_city_title() ?></option>
<? 			} ?>
										</optgroup>
<? 		} ?>
<? } ?>
									</select>
									<select name="type" style="width:220px;">
										<option value="">-- Выберите тип компании --</option>
<? foreach ($this->type_values as $value => $title) { ?>
										<option value="<?= $value ?>"<? if ($this->in_request('type', $value)) { ?> selected="selected"<? } ?>><?= $title ?></option>
<? } ?>
									</select>
								</div>
								<div class="floatleft"><img src="/image/sysimages/62.jpg" width="78" height="24" style="margin:0 0 0 20px; cursor:pointer" onclick="forms['faqform'].submit()" /></div>
							</form>
							<div class="clear"></div>
						</div>
<? if (count($this->partner_list)) { ?>
						<br />
						
						<div>
<? 		foreach ($this->partner_list as $partner) { ?>
							<b><?= $partner->get_partner_title() ?></b>
							<blockquote>
								Сайт компании: <a href="<?= $partner->get_partner_site() ?>"><?= $partner->get_partner_site() ?></a><br/>
								Город: <?= $this->city_list[$partner->get_partner_city()]->get_city_title() ?><br/>
								Адрес: <?= $partner->get_partner_address() ?><br/>
								Тип компании: <?= $this->type_values[$partner->get_partner_type()] ?><br/>
							</blockquote>
<? 		} ?>
						</div>
<? } ?>
					</div>
