					<div id="page_content_title">Где купить</div>
					<div class="content_ge"></div>
					<div class="content">
						<div>
							<form action="" method="post" name="faqform">
								<div class="floatleft">
									<select name="city" style="width:220px;">
										<option value="">-- Выберите город --</option>
<? foreach ($this->city_on_top_list as $city) { ?>
										<option value="<?= $city->get_id() ?>"<? if ($this->in_request('city', $city->get_id())) { ?> selected="selected"<? } ?> style="color: <?= $city->get_city_capital() ? 'black' : 'gray' ?>"><?= $city->get_city_title() ?></option>
<? } ?>
<? foreach ($this->region_list as $region) { ?>
<? 		if (count($this->city_by_region_list[$region->get_id()])) { ?>
										<optgroup label="<?= $region->get_region_title() ?>">
<? 			foreach ($this->city_by_region_list[$region->get_id()] as $city) { ?>
											<option value="<?= $city->get_id() ?>"<? if ($this->in_request('city', $city->get_id())) { ?> selected="selected"<? } ?> style="color: <?= $city->get_city_capital() ? 'black' : 'gray' ?>"><?= $city->get_city_title() ?></option>
<? 			} ?>
										</optgroup>
<? 		} ?>
<? } ?>
									</select>
									<select name="type" style="width:220px;">
										<option value="">-- Выберите тип компании --</option>
<? foreach ($this->type_values as $value => $title) { ?>
										<option value="<?= $value ?>"<? if ($this->in_request('type', $value)) { ?> selected="selected"<? } ?>><?= $title ?></option>
<? } ?>
									</select>
								</div>
								<div class="floatleft"><img src="/image/sysimages/62.jpg" width="78" height="24" style="margin:0 0 0 20px; cursor:pointer" onclick="forms['faqform'].submit()" /></div>
							</form>
							<div class="clear"></div>
						</div>
<? if (count($this->partner_list)) { ?>
						<br />
						
						<table style="width: 100%">
<? 		foreach ($this->partner_list as $partner) { ?>
							<tr>
								<td style="width: 50%; text-align: left; vertical-align: top;">
									<b><?= $this->escape($partner->get_partner_title()) ?></b>
									<blockquote>
										<a href="<?= $this->escape($partner->get_partner_site()) ?>"><?= $this->escape($partner->get_partner_site()) ?></a><br/>
										Телефон: <?= $this->escape($partner->get_partner_phone()) ?><br/>
										Тип компании: <?= $this->type_values[$partner->get_partner_type()] ?><br/>
										Город: <?= $this->city_list[$partner->get_partner_city()]->get_city_title() ?><br/>
<? 			$address_list = $partner->get_address_list(); ?>
<? 			if (count($address_list)) { ?>
										<blockquote>
<? 				foreach ($address_list as $address) { ?>
											<?= $this->escape($address->get_address_title()) ?><br/>
<? 				} ?>
										</blockquote>
<? 			} ?>
									</blockquote>
								</td>
								<td style="width: 50%; text-align: center; vertical-align: middle;">
<? 			if ($partner->get_partner_logo()) { ?>
									<img src="<?= $partner->get_partner_logo() ?>/r/200/200" alt=""/>
<? 			} else { ?>
									&nbsp;
<? 			} ?>
								</td>
							</tr>
<? 		} ?>
						</table>
<? } ?>
					</div>
