<? if( $this -> count > $this -> by_page ) { ?>
<div id='Pagediv'>
<? 		if( $this -> prev_page ) { ?>
	<a href='<?= $this->escape( $this -> prev_page['link'] ) ?>'><img src='/image/sysimages/pre.png' class='margin5' /></a>
<? 		} else { ?>
	<span class='span_a'><img src='/image/sysimages/pre_no.png' class='margin8' /></span>
<? 		} ?>
<? 		foreach( $this -> pages as $page ) { ?>
<? 			if( $page['link'] ) { ?>
<a href='<?= $this->escape( $page['link'] ) ?>' class='a_page'><? if ( $page['number'] ) { ?><?= $page['number'] ?><? } else { ?>&hellip;<? } ?></a>
<? 			} else { ?>
	<span class='span_b'><?= $page['number'] ?></span>
<? 			} ?>
<?		} ?>
<? 		if( $this -> next_page ) { ?>
	<a href='<?= $this->escape( $this -> next_page['link'] ) ?>'><img src='/image/sysimages/next.png' class='margin5' /></a>
<? 		} else { ?>
	<span class='span_a'><img src='/image/sysimages/next_no.png' class='margin8' /></span>
<? 		} ?>
	<div class='clear'></div>
</div>
<? } ?>
