					<div id="page_content_title">FAQ</div>
					<div class="content_ge"></div>
					<div class="content">
						<div class="newslist">
							<ul>
<? foreach ($this->item_list as $item) { ?>
<?= $item->get_faq_question() ?>
								<li>
									<b><a href="<?= url_for(array('controller' => 'support/faq', 'action' => 'item', 'id' => $item->get_id())) ?>">Ответ</a></b>
								</li>
<? } ?>
							</ul>
<?= $this -> pages ?>
							<div class="clear"></div>
						</div>
						<br />
						<br />
					</div>
